name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Grant execute permissions to gradlew
      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      # Step 5: Build the project
      - name: Build with Gradle
        run: ./gradlew clean build

      # Step 6: Run tests and generate coverage report
      - name: Run tests and generate coverage
        run: ./gradlew test jacocoTestReport

      # Step 7: Upload coverage report as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html

      # Step 8: Run SonarQube scan
      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: http://localhost:9000
          SONAR_TOKEN: squ_fd64a3d57b0d5812f8667c83c3234200ee56854e
        run: ./gradlew sonarqube
